### ISSUE TITLE
Некорректний автор доповіді

### ISSUE THREAD

**Issue by theshock** [listochkin/kyivjs#40]
Шановні, ви доповідь з якою я виступав ("Плагіни для JavaScript ігор"), кілька місяців тому раптово приписали іншому автору.

**Comment by sudodoki** [comment]
Спасибо большое, что сообщил. Прости, что так получилось с твоим докладом. Это произошло при переносе сайта с "все просто в хтмл" на "все спикеры лежат в конфигурации".  🙇

**Comment by tyv** [comment]
@theshock дякую! і вибач, це моя помилка

**Comment by theshock** [comment]
Вельми дякую. Так значно краще)
