### ISSUE TITLE
Change yandex maps to something else?

### ISSUE THREAD

**Issue by sudodoki** [listochkin/kyivjs#46]
Seems that script `https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Aeafde18a9ee9732ea1d244e06bc868d40597ecd99c160fcd95ec07782fb60f70&width=100%25&height=400&lang=ru_UA&scroll=true` won't be loading for people, who have those blocked on ISP level. Maybe, change it to google maps / OSM?

**Comment by tyv** [comment]
I hope they will fix that soon, but I am okay with changing it
