### ISSUE TITLE
Jan 21st Maintenance

### ISSUE THREAD

**Issue by sudodoki** [listochkin/kyivjs#7]
Add slides:
+ [x] @AlexeyRaspopov
+ [x] @galk-in
+ [x] @aqrln
+ [x] @s0rr0w

**Comment by galkin** [comment]
@sudodoki, my slides
https://galk-in.github.io/kyivjs-2017/#1

**Comment by alexeyraspopov** [comment]
@sudodoki, https://alexeyraspopov.github.io/the-right-way/

**Comment by aqrln** [comment]
@sudodoki https://aqrln.github.io/kyivjs-2017/

**Comment by sudodoki** [comment]
Closed via https://github.com/listochkin/kyivjs/commit/96035eabc96d3d4d704ac7a5a79002e7d647260b
